### ISSUE TITLE
Incorrect match results in certain conditions

### ISSUE THREAD

**Issue by ebzheng** [J-DM/Roth-Peranson#5]
This implementation can yield incorrect match results when there is a cycle of displacements such that an applicant is placed more than once.

A toy example to demonstrate (assuming 1 seat at each program):

```
Anderson,Beaudry,Chen,Davis
University,City,General,University
City,General,University,
General,University,City,
```

```
University,City,General
Chen,Anderson,Beaudry
Davis,Beaudry,Chen
Beaudry,Chen,Anderson
Anderson,,
```

Briefly, Davis displaces Anderson from University, which causes Anderson to propose successfully to City, displacing Beaudry. Beaudry then displaces Chen at General; Chen's next choice is University, where they are choice number 1, thus displacing Davis (who should go unmatched, with only 1 program listed).

However, the implementation incorrectly reports the following, with 2 matches to University:
```
{'Anderson': 'City', 'Beaudry': 'General', 'Chen': 'University', 'Davis': 'University'}
```

This is due to the recursion in `Student.find_next()` interacting with the non-atomic assignment to a program (L29, `self.current_place = program`). If the displacement chain intersects with itself (eg Davis being displaced above, when it was their initial placement that triggered the chain), the original assignment is incorrectly retained at the top of the recursion stack. Thus, Davis retains their seat at University in excess of the designed capacity.

I think deletion of L29 alone is sufficient. All of the paths in `apply_to` already set the matched program. I would prefer to explicitly set `replaced.current_place = None` in `Program.apply_to()` as well, but that may be unnecessary.

-----

**There is an additional error** in that L63,`candidate.curent_place = self`, clearly sets the incorrect field. Similarly in certain circumstances a candidate can match to the wrong program (since the correct program is in `curent_place` as opposed to `current_place`.

-----

Thanks for the implementation!

**Comment by J-DM** [comment]
Hey thanks for raising this!

I think these issues are addressed now in PR #6 

Added some better logging so you can see the match process in the CI tests here if you click on the "Run Tests" part of the logs:

https://github.com/J-DM/Roth-Peranson/actions/runs/6953300540/job/18918205742?pr=6

Your example has been added as a test case so should be caught in the future.

If you find anything else let me know!
